Add power support ppc64le and update versions
rvagg/node-errno pull request #34
Opened 2020-12-10 13:49 UTC by nagesh4193

Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing.

2020-12-10 17:42 UTC, ralphtheninja requested changes

2020-12-10 17:42 UTC, ralphtheninja commented on .travis.yml
> +  - 10
Lets drop the odd versions.

2020-12-10 17:43 UTC, ralphtheninja commented
@rvagg What do you think about releasing `v1.0.0` on this when dropping support for older node versions? Or just keep on publishing patches?

2020-12-14 02:29 UTC, rvagg commented
Oh, I don't know. This is one of those dependencies that people don't want to have to think about and a major bump will have big ripple effects.
Maybe we do both? Accept this PR and then do a bump, dropping old versions. I think the ppc64le folks are doing ecosystem rollouts for RedHat dependencies so would probably be happy if changes like this were fairly minimal and non-disruptive and I'm OK with that. I've already had to merge at least one of these PRs in one of my repos and I expect more.

2020-12-14 14:49 UTC, ralphtheninja commented
@nagesh4193 Mind adding _just_ adding

```
arch:
  - 4
  - amd64
  - ppc64le
```

And the new _even_ node versions? I.e. do not remove the old node versions. Then we can accept your PR, release a new patch version. After this we can publish a new major version with old node versions removed.

2020-12-15 13:31 UTC, nagesh4193 commented
@ralphtheninja I have made the changes as requested by adding old travis node_js versions and new even versions. Please let me know, if any other changes are required from my end. Thanks.

2020-12-15 17:27 UTC, ralphtheninja approved these changes

2020-12-15 17:29 UTC, ralphtheninja commented
@rvagg If you don't mind I'll release a new patch, then remove old node versions and release a new major. We can even keep a `0.x`-branch around if need be later.

2020-12-16 04:35 UTC, rvagg commented
sgtm, thanks!

2020-12-16 12:24 UTC, merged

2020-12-16 12:46 UTC, ralphtheninja commented
@nagesh4193 Published in `v0.1.8`